# TODO(gha): Move this into `setup-sentry` action when
# GitHub adds support for using other actions in composite actions
# as ideally this would do `uses: actions/cache` in here instead of workflow
name: 'pip Setup'
description: 'Installs pip and configures cache dir as output. This is hopefully temporary, until composite actions can use other actions.'

outputs:
  pip-cache-dir:
    description: 'Path to pip cache'
    value: ${{ steps.pip-cache.outputs.pip-cache }}

runs:
  using: 'composite'
  steps:
    - name: Setup default environment variables
      shell: bash
      run: |
        echo "PIP_DISABLE_PIP_VERSION_CHECK=on" >> $GITHUB_ENV

    - name: Install pip
      shell: bash
      run: |
        pip install --no-cache-dir --upgrade "pip>=20.0.2"

    - name: Get pip cache dir
      id: pip-cache
      shell: bash
      run: |
        echo "::set-output name=pip-cache::$(pip cache dir)"
