minVersion: "0.12.0"
github:
  owner: getsentry
  repo: sentry
releaseBranchPrefix: releases
changelog: CHANGES
changelogPolicy: auto
statusProvider:
  name: github
  config:
    contexts:
      - 'onpremise-builder (sentryio)'
targets:
  - name: github
  - name: pypi
  - id: Python 2 Image 
    name: docker
    source: us.gcr.io/sentryio/sentry
    target: getsentry/sentry
  - id: Python 3 Image
    name: docker
    source: us.gcr.io/sentryio/sentry
    sourceFormat: '{{{source}}}:{{{revision}}}-py3'
    target: getsentry/sentry
    targetFormat: '{{{target}}}:{{{version}}}-py3'

requireNames:
  - /^sentry-.+-py2.py3-none-any.whl$/
