name: py-deps
on:
  pull_request:
    # paths:
      # Matches all python files regardless of directory depth.
      # - requirements*.txt

jobs:
  check-python-deps:
    name: Check if python dependencies are upgradable
    runs-on: ubuntu-16.04

    env:
      PIP_DISABLE_PIP_VERSION_CHECK: on
      SENTRY_LIGHT_BUILD: 1
      SENTRY_SKIP_BACKEND_VALIDATION: 1
      MIGRATIONS_TEST_MIGRATE: 0

      # The hostname used to communicate with the PostgreSQL from sentry
      DATABASE_URL: postgresql://postgres:postgres@localhost/sentry

    # services:
      # postgres:
        # image: postgres:9.6
        # env:
          # POSTGRES_USER: postgres
          # POSTGRES_PASSWORD: postgres
        # ports:
          # # Maps tcp port 5432 on service container to the host
          # - 5432:5432
        # # needed because the postgres container does not provide a healthcheck
        # options: >-
          # --health-cmd pg_isready
          # --health-interval 10s
          # --health-timeout 5s
          # --health-retries 5

    steps:
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libxmlsec1-dev \
            libmaxminddb-dev

      # Checkout master first
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: f44d69055f61be13b1567cb43c249748b0d20505
          # ref: master

      # Python
      #   Use `.python-version` to avoid duplication
      #   XXX: can't actually read from .python-version because GitHub Actions
      #   does not support our version (2.7.16)
      #
      #   XXX: Using `2.7` as GHA image only seems to keep one minor version around and will break
      #   CI if we pin it to a specific patch version.
      - name: Set up outputs
        id: config
        env:
          MATRIX_INSTANCE: ${{ matrix.instance }}
        run: |
          echo "::set-output name=python-version::2.7"

      # setup python
      - name: Set up Python ${{ steps.config.outputs.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ steps.config.outputs.python-version}}

      # setup pip
      - name: Install pip
        run: |
          pip install --no-cache-dir --upgrade "pip>=20.0.2"

      # pip cache
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: pip cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - run: make setup-pyenv
        # env:
          # PGPASSWORD: postgres
      - name: Install python development dependencies
        run: make install-py-dev
        # run: |
          # pip install wheel # GitHub Actions does not have this installed by default (unlike Travis)
          # pip install -U -e ".[dev]"

      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: c5c69f5bb1e99b5eb34a6ff80a52767802509a7d

      # Install dependencies against to make sure everything works
      - name: Install python development dependencies (on branch)
        run: make install-py-dev
